# Force the base to resolve as amd64 even on arm64 hosts
FROM --platform=linux/amd64 ghcr.io/alope107/gba-quickstart-devcontainer:latest

# Interested in changing the devcontainer for your own purposes?
# Don't edit this Dockerfile, edit .devcontainer/Dockerfile instead, and edit devcontainer.json
# to point to "Dockerfile" instead of the shim